server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: auth-service
          uri: lb://USER
          predicates:
            - Path=/auth/**

      - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
