server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:3001/FREEPDB1
    username: system
    password: "0000"
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
